### ISSUE TITLE
Compiling Bit2byte with Pytorch 1.1

### ISSUE THREAD

**Issue by tvogels** [PermiJW/signSGD-with-Majority-Vote#2]
Hi,

Thanks for sharing your code. I would like to use your `bit2byte` extension to compare against 'SignSGD with Majority Vote' in an academic paper. I'm having some issues compiling the extension with Pytorch 1.1, and am wondering if you could give me some hints.

It seems that the include was changed from `torch/torch.h` to `torch/extension.h` and the namespace `at` was changed for `torch`.

I get errors from the lines with `CUDA`:

```
bit2byte.cpp: In function ‘at::Tensor packing(at::Tensor)’:
bit2byte.cpp:7:41: error: ‘class at::DeprecatedTypeProperties’ has no member named ‘rand’
     auto a = torch::CUDA(torch::kFloat).rand({2});
```

I am trying to find a solution, but feel that I don't perfectly understand the code. Why is the vector with `[1, -2]` initialized randomly?

Any help would be greatly appreciated.

**Comment by tvogels** [comment]
This seems to work:

```cpp
#include <iostream>
#include <torch/extension.h>

torch::Tensor packing(torch::Tensor src)
{
    //src is dim(32*-1) IntTensor
    //make sure shift just gnerates zero

    auto options = torch::TensorOptions()
                       .dtype(torch::kInt)
                       .device(src.device());
    torch::Tensor a = torch::zeros(2, options);
    a[0] = 1;
    a[1] = -2;
    auto mask_0 = a[0];
    auto mask_1 = a[1];

    src[0].__irshift__(mask_0);
    src[0].__iand__(mask_0);

    for (int i = 1; i < 32; i++)
    {
        src[0].__ilshift__(mask_0);
        src[0].__iand__(mask_1);
        src[i].__irshift__(mask_0);
        src[i].__iand__(mask_0);
        src[0].__ior__(src[i]);
    }

    return {src[0]};
}

torch::Tensor unpacking(torch::Tensor src, torch::Tensor dst)
{
    //src is dim(1*-1) IntTensor
    //dst is dim(32*-1) IntTensor(ones)
    auto options = torch::TensorOptions()
                       .dtype(torch::kInt)
                       .device(src.device());
    torch::Tensor a = torch::zeros(1, options);
    a[0] = 1;
    auto mask_0 = a[0];

    for (int i = 31; i >= 0; i--)
    {
        dst[i].__iand__(src);
        dst[i].__ilshift__(mask_0);
        src.__irshift__(mask_0);
    }

    return {dst};
    //outside we should -(dst-1)
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m)
{
    m.def("packing", &packing, "packing");
    m.def("unpacking", &unpacking, "unpacking");
}
```

Does this look reasonable to you? Maybe there is a more elegant way to get two scalars on the GPU ... Would you like me to open a pull request?

**Comment by jiaweizzhao** [comment]
Hi Thijs,

It looks great! Please feel free to open a pull request.

About a[0]= 1, a[1] = -2 in the function of packing, you can look them in the binary format:

a[0] = 000....001 (32-bits)
a[1] = 111....110 (32-bits)

They will serve as binary masks for source packing tensor when using 'and' or 'or' bit-level functions.
